"""add relationship

Revision ID: 050aa112e6b0
Revises: 34f3f8df4357
Create Date: 2024-05-19 20:09:43.102981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050aa112e6b0'
down_revision: Union[str, None] = '34f3f8df4357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_persons', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'contact_persons', ['person_id'])
    op.create_foreign_key(None, 'contact_persons', 'persons', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact_persons', type_='foreignkey')
    op.drop_constraint(None, 'contact_persons', type_='unique')
    op.drop_column('contact_persons', 'person_id')
    # ### end Alembic commands ###
