"""update models

Revision ID: 175008861148
Revises: 5a889341abf2
Create Date: 2024-05-19 20:38:14.325065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175008861148'
down_revision: Union[str, None] = '5a889341abf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('subject', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_emails_subject'), 'emails', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_subject'), table_name='emails')
    op.drop_column('emails', 'subject')
    # ### end Alembic commands ###
