"""add subject in contact model

Revision ID: 5a889341abf2
Revises: 050aa112e6b0
Create Date: 2024-05-19 20:24:32.928113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a889341abf2'
down_revision: Union[str, None] = '050aa112e6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_persons', sa.Column('subject', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_contact_persons_subject'), 'contact_persons', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_persons_subject'), table_name='contact_persons')
    op.drop_column('contact_persons', 'subject')
    # ### end Alembic commands ###
