"""update email model

Revision ID: 66c64cc3f0fc
Revises: 175008861148
Create Date: 2024-05-19 20:57:06.743630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c64cc3f0fc'
down_revision: Union[str, None] = '175008861148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'emails', 'persons', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'person_id')
    # ### end Alembic commands ###
